import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import Header from './components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// components
import Navbar from './components/Navbar'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='${inter.className} h-screen'>
        <div className='bg-primary w-full h-screen text-neutral bg-cover bg-no-repeat relative'>
        <Navbar/>
        <Header/>
        {children}
        </div>
        </body>
    </html>
  )
}
